jobs:
  - name: build-artifact
    serial_groups: [version]
    serial: true
    plan:
    - get: git-repo
      trigger: true
    - get: version
      params: { pre: rc }
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
      timeout: 5m
    - put: release-candidate
      params:
        file: artifact-dir/meetup*.jar
    - put: version
      params: {file: version/number}

  - name: deploy-to-pcf
    serial_groups: [version]
    plan:
    - aggregate:
      - get: version
        passed: [build-artifact]
        trigger: true
      - get: release-candidate
        passed: [build-artifact]
      - get: git-repo
        passed: [build-artifact]
    - put: deploy-test-app
      params:
        manifest: git-repo/manifest.yml
        current_app_name: cf-concourse-demo
        path: release-candidate/meetup*.jar

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-test-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: {{S3_VERSION_FILE}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0

- name: release-candidate
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: {{S3_PIPELINE_ARTIFACTS}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
